app/__init__.py
from flask import Flask

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)

    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

app/main/routes.py
from base64 import b64encode
from io import BytesIO
import cv2
from PIL import Image
from flask import  Response, flash
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from werkzeug.exceptions import abort
from wtforms import FileField , SubmitField
from app.main import main_bp
from app.main.camera import Camera
from source.img import image_detect
from source.video_detector import video_detect
from flask import  redirect, url_for
from source.api import *
from source.cal_vol import imagedtct
import sqlite3
import hashlib
import sqlite3 as sql
from flask import render_template,render_template_string
from flask import request
import models as dbHandler

def insertUser(username,password):
    con = sql.connect("C:/Users/User/Desktop/project/app/static/User.db")
    cur = con.cursor()
    cur.execute("INSERT INTO users (username,password) VALUES (?,?)", (username,password))
    con.commit()
    con.close()

def retrieveUsers():
	con = sql.connect("C:/Users/User/Desktop/project/app/static/User.db")
	cur = con.cursor()
	cur.execute("SELECT username, password FROM users")
	users = cur.fetchall()
	con.close()
	return users

def check_password(hashed_password, user_password):
    return hashed_password == hashlib.md5(user_password.encode()).hexdigest()

def validate(username, password):
    con = sqlite3.connect('C:/Users/User/Desktop/project/app/static/User.db')
    completion = False
    with con:
                cur = con.cursor()
                cur.execute("SELECT * FROM Users")
                rows = cur.fetchall()
                for row in rows:
                    dbUser = row[0]
                    dbPass = row[1]
                    if dbUser==username:
                        completion=check_password(dbPass, password)
    return completion


@main_bp.route("/")
def home_page():
    return render_template("index.html")



@main_bp.route('/sign_up', methods=['POST', 'GET'])
def sign_up():
    if request.method=='POST':
        username = request.form['username']
        password = request.form['password']
        dbHandler.insertUser(username, password)
        users = dbHandler.retrieveUsers()
        return render_template('sign_up.html', users=users)
    else:
        return render_template('sign_up.html')

@main_bp.route('/live_detector')
def live_detector():
    return render_template("live_detector.html")
def gen(camera):

    while True:
        frame = camera.get_frame()
        frame_processed = video_detect(frame)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')

@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(
        Camera()
    ),
        mimetype='multipart/x-mixed-replace; boundary=frame')
def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good


@main_bp.route("/image-detector", methods=["GET", "POST"])
def image_detection():
    return render_template("image_detector.html",
                           form=PhotoMaskForm())


@main_bp.route("/image-processing", methods=["POST"])
def image_processing():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    array_image = image_detect(image)
    rgb_image = cv2.cvtColor(array_image, cv2.COLOR_BGR2RGB)
    image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')
        return base64img


# form
class PhotoMaskForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png'], 'The allowed extensions are: .jpg, .jpeg and .png')])

    submit = SubmitField('Estimate')

@main_bp.route("/cal_vol", methods=["GET", "POST"])
def cal_vol():
    return render_template("cal_vol.html",
                           form=PhotoMaskForm())
@main_bp.route("/image-pro", methods=["POST"])
def image_pro():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    array_image = imagedtct(image)
    rgb_image = cv2.cvtColor(array_image, cv2.COLOR_BGR2RGB)
    image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')
        return base64img
@main_bp.route('/poid')
def poid():
    return render_template('poid.html')
@main_bp.route('/nutrition')
def nutrition():
    return render_template('nutrition.html')

@main_bp.route('/about')
def about_page():
    return render_template("about.html")

@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        completion = validate(username, password)
        if completion ==False:
            error = 'Invalid Credentials. Please try again.'
        else:
            return redirect(url_for('secret'))
    return render_template('login.html', error=error)

@main_bp.route('/secret')
def secret():
    return "You have successfully logged in"

app/templates/cal_vol.html
{% extends "template.html" %}
{% block content %}


<head>
	<title>Be Healthy</title>
	<link rel="stylesheet" type="text/css" href="/static/styles/bootstrap4/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/styles/main_styles.css">
</head>
<div class="jumbotron" style="background-color:#0A4100;">
    <div class="row">

    </div>
</div>
<div class="row">
        <div class="col-12"><strong>
            <h3 class="navbar navbar-expand-lg navbar-dark " style="color: #286833 ;">Try the volume / calorie estimation on your ingredients to further narrow down how many calories you are consuming each day. </h3></strong>
        </div>
    </div>
<header class="header">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="header_content d-flex flex-row align-items-center justify-content-start">
							<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
								<div class="logo"><a href="index.html"> <h3> Eat Healthy</h3></a></div>
								<nav class="main_nav">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="/"><p style="background-color:#;">Home</a></li>
										<li><a href="/nutrition"><p style="background-color: #;">Calorie/day</a></li>
										<li><a href="/live_detector"><p style="background-color: #;">AI Live Dish Analysis </a></li>
										<li><a href="/image-detector"><p style="background-color: #;">AI Image Dish Analysis </a></li>
										<li><a href="/cal_vol"><p style="background-color: #;">AI vol/calorie estimation</a></li>
                                        <li><a href="/poid"><p style="background-color: #;">Ideal weight</a></li>

										</ul>
								</nav>

								<!-- Hamburger -->

								<div class="hamburger ml-auto">
									<i class="fa fa-bars" aria-hidden="true"></i>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/55.jpg" id="image-preview" style="max-width:600px"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-12 d-flex justify-content-center">

                <form enctype="multipart/form-data" id="image-form" method="POST">
                    <div class="row" id="form-row">
                        <div class="col-12">
                            {{ form.csrf_token() }}

                            {{ form.image.label(class="custom-file-label") }}
                            {% if form.image.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.image.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="custom-file">
                                {{ form.image(class="custom-file-input",
                                id="new-image", onchange="previewImage(event)") }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-12 d-flex justify-content-center">
                            {{ form.submit(class="btn btn-primary", id ="submit", disabled=True)}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr>

        <div class="row mb-5">
            <p>I hope you all good health:</p>
            <p class="d-flex mx-auto lead text-danger"><strong>stay healthy!</strong>.</p>
            <p></p>
        </div>
    </div>
</div>

{% endblock %}
{% block custom_js %}
<script>
var previewImage = function(event) {
    var element_id = "image-preview";
    var preview = document.getElementById(element_id);
    preview.src = URL.createObjectURL(event.target.files[0]);
    preview.style.display = "block";
    $("#submit").prop("disabled",false);
};

$(function() {
        $("#submit").each(function(index){
            $(this).on('click', function(e) {

                var url = "{{ url_for('main.image_pro') }}";

                // Form data
                var formData = new FormData();

                // Add form data
            $('#image-form').serializeArray().forEach(
                function(item, index) {
                    formData.append(item.name, item.value);
                }
            );
                // Add the files
                var image = $('#new-image')[0].files[0];
                formData.append('image', image);

                // AJAX query to the endpoint for deletion
                $.ajax({
                    type: "POST", // POST HTTP
                    url:  url +'',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function(response) {

                        $("#image-preview").attr("src", response);
                        $("#submit").replaceWith('<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>');
                        $("#form-row").remove();
                    },
                    error: function(response){
                        location.reload();
                        // Redirect to this page
                    }
                });

                return false;
            })
        })
    })
</script>
{% endblock %}


						<div class="home_slider_content_container">
							<div class="container">
								<div class="row">
									<div class="col">
										<div class="home_slider_content">
											<div class="home_title">
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>


<div class="footer">
        <div class="py-4 bg-dark text-white-50">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <p>You can follow me here:</p>
                        <div class="row">
                            <div class="col-4">
                                <a href="https://www.linkedin.com/in/galileo-parise-34311198/" class="footer-link">
                                    <i class="fa fa-linkedin-square my-auto mx-2" aria-hidden="true"></i> Linkedin
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="#" class="footer-link">
                                    <i class="fa fa-medium mx-2 my-auto" aria-hidden="true"></i>Medium
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="mailto:parise.galileo@gmail.com?subject=Mask%20detector" class="footer-link">
                                    <i class="fa fa-envelope my-auto mx-2" aria-hidden="true"></i> Mail
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/image_detector.html
{% extends "template.html" %}
{% block content %}


<head>
	<title>Be Healthy</title>
	<link rel="stylesheet" type="text/css" href="/static/styles/bootstrap4/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/styles/main_styles.css">
</head>
<div class="jumbotron" style="background-color:#0A4100;">
    <div class="row">

    </div>
</div>
<div class="row">
        <div class="col-12"><strong>
            <h3 class="navbar navbar-expand-lg navbar-dark " style="color: #286833 ;">Try the calorie estimator on images!! </h3></strong>
        </div>
    </div>
<header class="header">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="header_content d-flex flex-row align-items-center justify-content-start">
							<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
								<div class="logo"><a href="index.html"> <h3> Eat Healthy</h3></a></div>
								<nav class="main_nav">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="/"><p style="background-color:#;">Home</a></li>
										<li><a href="/nutrition"><p style="background-color: #;">Calorie/day</a></li>
										<li><a href="/live_detector"><p style="background-color: #;">AI Live Dish Analysis </a></li>
										<li><a href="/image-detector"><p style="background-color: #;">AI Image Dish Analysis </a></li>
										<li><a href="/cal_vol"><p style="background-color: #;">AI vol/calorie estimation</a></li>
                                        <li><a href="/poid"><p style="background-color: #;">Ideal weight</a></li>

										</ul>
								</nav>

								<!-- Hamburger -->

								<div class="hamburger ml-auto">
									<i class="fa fa-bars" aria-hidden="true"></i>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</header>

<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/33.PNG" id="image-preview" style="max-width:600px"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-12 d-flex justify-content-center">

                <form enctype="multipart/form-data" id="image-form" method="POST">
                    <div class="row" id="form-row">
                        <div class="col-12">
                            {{ form.csrf_token() }}

                            {{ form.image.label(class="custom-file-label") }}
                            {% if form.image.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.image.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="custom-file">
                                {{ form.image(class="custom-file-input",
                                id="new-image", onchange="previewImage(event)") }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-12 d-flex justify-content-center">
                            {{ form.submit(class="btn btn-primary", id ="submit", disabled=True)}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr>


        <div class="row mb-5">
            <p>I hope you all good health</p>
            <p class="d-flex mx-auto lead text-danger"><strong>stay healthy!</strong>.</p>
            <p></p>
        </div>
    </div>
</div>

{% endblock %}
{% block custom_js %}
<script>
var previewImage = function(event) {
    var element_id = "image-preview";
    var preview = document.getElementById(element_id);
    preview.src = URL.createObjectURL(event.target.files[0]);
    preview.style.display = "block";
    $("#submit").prop("disabled",false);
};

$(function() {
        $("#submit").each(function(index){
            $(this).on('click', function(e) {

                var url = "{{ url_for('main.image_processing') }}";

                // Form data
                var formData = new FormData();

                // Add form data
            $('#image-form').serializeArray().forEach(
                function(item, index) {
                    formData.append(item.name, item.value);
                }
            );
                // Add the files
                var image = $('#new-image')[0].files[0];
                formData.append('image', image);

                // AJAX query to the endpoint for deletion
                $.ajax({
                    type: "POST", // POST HTTP
                    url:  url +'',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function(response) {

                        $("#image-preview").attr("src", response);
                        $("#submit").replaceWith('<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>');
                        $("#form-row").remove();
                    },
                    error: function(response){
                        location.reload();
                        // Redirect to this page
                    }
                });

                return false;
            })
        })
    })
</script>
{% endblock %}


						<div class="home_slider_content_container">
							<div class="container">
								<div class="row">
									<div class="col">
										<div class="home_slider_content">
											<div class="home_title">
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>


<div class="footer">
        <div class="py-4 bg-dark text-white-50">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <p>You can follow me here:</p>
                        <div class="row">
                            <div class="col-4">
                                <a href="https://www.linkedin.com/in/galileo-parise-34311198/" class="footer-link">
                                    <i class="fa fa-linkedin-square my-auto mx-2" aria-hidden="true"></i> Linkedin
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="#" class="footer-link">
                                    <i class="fa fa-medium mx-2 my-auto" aria-hidden="true"></i>Medium
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="mailto:parise.galileo@gmail.com?subject=Mask%20detector" class="footer-link">
                                    <i class="fa fa-envelope my-auto mx-2" aria-hidden="true"></i> Mail
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/templates/live_detector.html
{% extends "template.html" %}
{% block content %}

<body style="background-color:#FFFFF0;">

<head>
	<title>Be Healthy</title>
	<link rel="stylesheet" type="text/css" href="/static/styles/bootstrap4/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/styles/main_styles.css">
</head>
<div class="jumbotron" style="background-color:#0A4100;">
    <div class="row">

    </div>
</div>
<div class="row">
        <div class="col-12"><strong>
            <h3 class="navbar navbar-expand-lg navbar-dark " style="color: #286833 ;">Welcome to the calorie estimator live for healthy life!  </h3></strong>
        </div>
    </div>
	<div class="super_container">
<header class="header">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="header_content d-flex flex-row align-items-center justify-content-start">
							<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
								<div class="logo"><a href="index.html"> <h3> Eat Healthy</h3></a></div>
								<nav class="main_nav">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="/"><p style="background-color:#;">Home</a></li>
										<li><a href="/nutrition"><p style="background-color: #;">Calorie/day</a></li>
										<li><a href="/live_detector"><p style="background-color: #;">AI Live Dish Analysis </a></li>
										<li><a href="/image-detector"><p style="background-color: #;">AI Image Dish Analysis </a></li>
										<li><a href="/cal_vol"><p style="background-color: #;">AI vol/calorie estimation</a></li>
                                        <li><a href="/poid"><p style="background-color: #;">Ideal weight</a></li>

										</ul>
								</nav>

								<!-- Hamburger -->

								<div class="hamburger ml-auto">
									<i class="fa fa-bars" aria-hidden="true"></i>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/44.PNG"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                                                                                        aria-hidden="true"></i> Start
                </button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                                                                                    aria-hidden="true"></i> Stop
                </button>
            </div>
        </div>
        <hr>


        <div class="row mb-5">
            <p>I hope you all good health.</p>
            <p class="d-flex mx-auto lead text-danger"><strong>stay healthy!</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
    function stop(){
        $("img").attr("src", "/static/images/44.PNG");
        $("#stop").attr("class","btn btn-danger active");

        $("#start").attr("class","btn btn-outline-success");
    }
    function start(){
        $("img").attr("src", "{{url_for('main.video_feed')}}");
        $("#start").attr("class","btn btn-success active");

        $("#stop").attr("class","btn btn-outline-danger");
    }

</script>

{% endblock %}

						<script src="/static/js/custom.js"></script>
        <div class="home_slider_content_container">
							<div class="container">
								<div class="row">
									<div class="col">
										<div class="home_slider_content">
											<div class="home_title">
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
	</body>
<div class="footer">
        <div class="py-4 bg-dark text-white-50">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <p>You can follow me here:</p>
                        <div class="row">
                            <div class="col-4">
                                <a href="https://www.linkedin.com/in/galileo-parise-34311198/" class="footer-link">
                                    <i class="fa fa-linkedin-square my-auto mx-2" aria-hidden="true"></i> Linkedin
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="#" class="footer-link">
                                    <i class="fa fa-medium mx-2 my-auto" aria-hidden="true"></i>Medium
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="mailto:parise.galileo@gmail.com?subject=Mask%20detector" class="footer-link">
                                    <i class="fa fa-envelope my-auto mx-2" aria-hidden="true"></i> Mail
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/templates/login.html
<body style="background-color:#FFFFF0;">

<head>
	<title>Be Healthy</title>
	<link rel="stylesheet" type="text/css" href="/static/styles/bootstrap4/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
	<link rel="stylesheet" type="text/css" href="/static/plugins/OwlCarousel2-2.2.1/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/styles/main_styles.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" media="screen">

</head>
<div class="jumbotron" style="background-color:#0A4100;">
    <div class="row">

    </div>
</div>
<div class="row">
        <div class="col-12"><strong>
            <h2 class="navbar navbar-expand-lg navbar-dark " style="color: #286833 ;">Please login here... </h2></strong>
        </div>
    </div>
	<body class="super_container">
<header class="header">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="header_content d-flex flex-row align-items-center justify-content-start">
							<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
								<div class="logo"><a href="index.html"> <h3> Eat Healthy</h3></a></div>
								<nav class="main_nav">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="/"><p style="background-color:#;">Home</a></li>
										<li><a href="/nutrition"><p style="background-color: #;">Calorie/day</a></li>
										<li><a href="/live_detector"><p style="background-color: #;">AI Live Dish Analysis </a></li>
										<li><a href="/image-detector"><p style="background-color: #;">AI Image Dish Analysis </a></li>
										<li><a href="/cal_vol"><p style="background-color: #;">AI vol/calorie estimation</a></li>
                                        <li><a href="/poid"><p style="background-color: #;">Ideal weight</a></li>

										</ul>
								</nav>

								<!-- Hamburger -->

								<div class="hamburger ml-auto">
									<i class="fa fa-bars" aria-hidden="true"></i>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
<body>
    <div class="container">
      <br>
      <form action="" method="post">
        <input type="text" placeholder="Username" name="username" value="{{
          request.form.username }}">
         <input type="password" placeholder="Password" name="password" value="{{
          request.form.password }}">
        <input class="btn btn-default" type="submit" value="Login">
      </form>
      {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}
      {% endif %}
    </div>

</body></body>